### ISSUE TITLE
ダウンロードで躓く人がいる

### ISSUE THREAD

**Issue by nazonoSAUNA** [amate/InputPipePlugin#4]
GitHubをあまり使ったことのない人がビルド済みzipにたどり着かないことがあるようです。（某プラグインの影響でソースコードからDL出来るものと勘違いしている人もいるよう）

https://github.com/hebiiro/AviUtl-Plugin-SplitWindow のようにReleaseへのリンクを書くことは可能でしょうか？

**Comment by amate** [comment]
ダウンロードリンクへの説明を追加しました
