### ISSUE TITLE
緑一色しか表示されない＆read_audioのエラーが出る

### ISSUE THREAD

**Issue by nazonoSAUNA** [amate/InputPipePlugin#5]
発生ファイル
https://commons.nicovideo.jp/material/nc98732

発生条件
InputPipePluginなし→問題なし
名前付きパイプ→問題なし
共有メモリ→問題あり

L-SMASH Worksの設定で
https://scrapbox.io/Mr-Ojii/L-SMASH_Works_HW%E3%83%87%E3%82%B3%E3%83%BC%E3%83%89
cuvidを入れていると共有メモリでも問題なし

エラー情報
code : EXCEPTION_ACCESS_VIOLATION (0xc0000005)
address : 0x5fb28f5a (InputPipePlugin.aui + 0x00028f5a)
func_name : INPUT_PLUGIN_TABLE::func_close()

code : EXCEPTION_ACCESS_VIOLATION (0xc0000005)
address : 0x5fad8077 (InputPipePlugin.aui + 0x00028077)
func_name : INPUT_PLUGIN_TABLE::func_open()

code : * C++ exception (0xe06d7363)
address : 0x759de292 (KERNELBASE.dll + 0x0012e292)
func_name : INPUT_PLUGIN_TABLE::func_read_video()

code : * C++ exception (0xe06d7363)
address : 0x759de292 (KERNELBASE.dll + 0x0012e292)
func_name : INPUT_PLUGIN_TABLE::func_close()

(試していたところタイトルにしてしまったread_audioは再現できませんでしたが事例を貼っておきますhttps://twitter.com/haku_asahi/status/1624767258030653443)
など様々確認しています（同じフレームに別の動画などを置くことで発生します）

参考情報として、拡張編集へD&Dした時に音声ファイルオブジェクトが生成されない何かしらおかしなファイルです
但し、動画ファイルオブジェクトを単体で設置→参照ファイルから読み込みをしてもエラーがあったため、音声が設置されないことが直接的な原因ではなさそうです

宜しくお願いします

**Comment by amate** [comment]
修正しました
