### ISSUE TITLE
x64化

### ISSUE THREAD

**Issue by SysVR** [amate/InputPipePlugin#9]
いろいろと関数をx64関数に書き直す必要がありますが、
L-SMASH-Works_rev1096_Mr-Ojii_Mr-Ojii_AviUtl
で8K動画を読み込むとx86ではInputPipeMain.exeのメモリ使用量がギリギリになるので、
可能であればx64版も作成して頂ければ幸いです。

(inputプラグイン側もx64化する必要があると思いますが、少なくともMr-Ojiiさんはこのプラグインを利用してx64化しようとしたことがあるとの事です。)

**Comment by amate** [comment]
v2.0で64bit版を追加しました
なお動作確認できていないので正常に動くかどうかは不明です
